### ISSUE TITLE
the last case in example of use in README seems to be wrong

### ISSUE THREAD

**Issue by ntala** [Arkaeriit/math-parse#1]
Hello,
I am very new to rust, so I may be wrong but it seems that this doesn't work :  
```
    let parsed = MathParse::parse("(2+3)*2/5").unwrap().to_tree();
    println!("{parsed}"); // Prints (((2 + 3) * 2) / 5)
```
The result of to_tree(), thas is of type `Result<Tree, MathParseErrors>`, need to be unwrap to get a `Tree`, that implements the trait `std::fmt::Display` :
```
    let parsed = MathParse::parse("(2+3)*2/5").unwrap().to_tree().unwrap();
    println!("{parsed}"); // Prints (((2 + 3) * 2) / 5)
```

**Comment by Arkaeriit** [comment]
You are absolutely right, it's a mistake on my part.
Thanks for pointing it out, I fixed it.
